### ISSUE TITLE
Bug in follow-up date

### ISSUE THREAD

**Issue by apragati22** [devansh83/DocuMed#92] opened 2024-04-05 07:16 UTC
The follow-up date feature for the doctor allows him/her to add any backdate also, which should not be possible. Also, if the exact same Date-Time is added more than once, the system does not evoke any error message. It is just added there itself.

**Comment by Tanush247** [comment] 2024-04-07 11:44
We have updated the follow-up date feature as follows:

When a doctor clicks on the 'Add Follow-up Date' button for a patient and enters a valid date-time, all previous appointments scheduled between the doctor and patient are removed, and a new appointment with the entered date-time is added.

This aligns with real-life scenarios where doctors may need to update the follow-up date given to a patient. I am closing this issue for now. Please verify, and if the issue persists, feel free to reopen it.

**Closed as completed by Tanush247** 2024-04-07 11:44 UTC

**Comment by Poojal04** [comment] 2024-04-12 06:47
The issue is not resolved. I was able to add a back date when adding an appointment.

**Comment by Tanush247** [comment] 2024-04-12 17:42
We have updated the feature in the following way:

If the doctor enters a valid datetime before the system's current datetime an error message "The date entered is in past" is shown. The doctor can update an already existing appointment and schedule it to a previous time provided the new time is in future.
